<?php

namespace Softok2\RestApiClient\Providers;

use Illuminate\Support\ServiceProvider as BaseServiceProvider;
use Softok2\RestApiClient\Console\Commands\GenerateApiClientResource;
use Softok2\RestApiClient\Services\RestClientInterface;
use Softok2\RestApiClient\Services\RestClientService;

final class ServiceProvider extends BaseServiceProvider
{
    public function boot(): void
    {
        $this->publishes([
            __DIR__ . '/../../config/rest-api-client.php' => config_path('rest-api-client.php'),
        ], 'config');

        if ($this->app->runningInConsole()) {
            $this->commands([
                GenerateApiClientResource::class
            ]);
        }
    }

    public function register(): void
    {
        // CCM API Service ...
        $this->app->bind(RestClientInterface::class, function () {
            $config = config('rest-api-client');
            return new RestClientService(
                $config['url'],
                $config['timeout'],
                $config['secret']
            );
        });

        parent::register(); // TODO: Change the autogenerated stub
    }
}
